### ISSUE TITLE
jsonGet fails if response is empty

### ISSUE THREAD

**Issue by NikolaR** [psexton/missing-http#4]
jsonGet fails in an unexpected manner when response from web application is empty.

In specific, logic of the application was to perform get, and if HTTP 200 is returned, operation is considered successful. Otherwise it failed, and may return a response.

Error log follows:

```
Error using http.jsonGet (line 29)
Java exception occurred:
java.lang.IllegalArgumentException: Entity may not be null

    at net.psexton.ext.org.apache.http.util.Args.notNull(Args.java:48)

    at net.psexton.ext.org.apache.http.util.EntityUtils.toString(EntityUtils.java:213)

    at net.psexton.ext.org.apache.http.util.EntityUtils.toString(EntityUtils.java:288)

    at net.psexton.missinghttp.MatlabShim.jsonGet(MatlabShim.java:172)
```

**Comment by psexton** [comment]
Good catch! The same fix probably needs to be added to `MatlabShim#filePut`, `MatlabShim#jsonPost`, `MatlabShim#jsonPut`, and `MatlabShim#multipartPost`, since those do the same thing with the `EntityResponse`.

**Comment by NikolaR** [comment]
Yes. I've already did it for my purposes, and I've sent you a pull request with the changes.
